#!/usr/bin/env python3
"""Parse ПАРТНЬОРИ.txt (Microinvest partner registry) -> CSV + SQL UPSERT."""
from __future__ import annotations
import csv
import re
import sys
from pathlib import Path

SRC = Path("/Users/magic/Projects/mert-m/data-imports/partneri.utf8.txt")
OUT_CSV = Path("/Users/magic/Projects/mert-m/data-imports/partneri.csv")
OUT_SQL = Path("/Users/magic/Projects/mert-m/data-imports/partneri-import.sql")

# Column boundaries (character positions, derived from header line 7)
COLS = {
    "name":        (3,  33),    # Наименование на партньора (30 chars)
    "eik":         (34, 46),    # Идент.номер (12 chars)
    "vat":         (47, 61),    # Идент.ном.ЗДДС (14 chars)
    "address":     (62, 112),   # Адрес на партньора (50 chars)
    "phone":       (113, 163),  # Телефони и факс (50 chars)
    "responsible": (164, 189),  # Материално отговорно лице (25 chars)
    "other":       (190, 250),  # Друга информация (60 chars)
}

# Skip header / footer / separator markers
SKIP_TOKENS = ("РЕГИСТЪР", "Дата :", "стр.")
HEADER_PREFIX = "   Наименование на партньора"
SEP_RE = re.compile(r"^\s*[-=]+\s*$")
COL_NUM_RE = re.compile(r"^\s*\d(\s+\d)+\s*$")  # "1   2  2  3  4  5  6"


def normalize_eik(s: str) -> str:
    return s.replace(" ", "").strip() if s else ""


def main() -> int:
    rows = []
    seen_eik = set()
    duplicates = []
    orphans = []
    no_eik = []

    with SRC.open(encoding="utf-8") as f:
        for lineno, raw in enumerate(f, start=1):
            line = raw.rstrip("\r\n")
            if not line.strip():
                continue
            if any(t in line for t in SKIP_TOKENS):
                continue
            if line.startswith(HEADER_PREFIX):
                continue
            if SEP_RE.fullmatch(line):
                continue
            if COL_NUM_RE.fullmatch(line):
                continue

            def slc(field):
                a, b = COLS[field]
                return line[a:b].strip() if len(line) > a else ""

            name = slc("name")
            eik = normalize_eik(slc("eik"))
            vat = slc("vat")
            address = slc("address")
            phone = slc("phone")
            responsible = slc("responsible")
            other = slc("other")

            if not name:
                continue

            # Orphan rows: name is just digits (EIK), nothing else
            if name.isdigit() and not eik and not vat and not address:
                orphans.append((lineno, name))
                continue

            # Some rows put the address in the "phone" column. If address is
            # empty but phone has content that looks like an address (starts
            # with гр./с./ГР./УЛ./бул.), shift it into address.
            if not address and phone and re.match(r"^(гр\.|с\.|ГР\.|С\.|ул\.|УЛ\.|бул\.|БУЛ\.|ж\.к\.|ЖК)", phone):
                address = phone
                phone = ""

            # Skip rows without EIK (per user request)
            if not eik:
                no_eik.append((lineno, name))
                continue

            # Dedup by EIK (Microinvest sometimes has duplicate-ish entries
            # like "ИНТЕРМО ООД" + "ИНТЕРМО ЕООД" with related EIKs).
            if eik in seen_eik:
                duplicates.append((lineno, eik, name))
                continue
            seen_eik.add(eik)

            rows.append({
                "lineno": lineno,
                "name": name,
                "eik": eik,
                "vat": vat,
                "address": address,
                "phone": phone,
                "responsible": responsible,
                "other": other,
            })

    # ---- CSV ----
    with OUT_CSV.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["name", "eik", "vat_number", "address", "phone", "responsible_person", "other"])
        for r in rows:
            w.writerow([r["name"], r["eik"], r["vat"], r["address"], r["phone"], r["responsible"], r["other"]])

    # ---- SQL ----
    sql = []
    sql.append("-- Partners import — generated by parse_partneri.py")
    sql.append(f"-- Source: {SRC.name}")
    sql.append(f"-- Rows: {len(rows)} (orphans: {len(orphans)}, duplicates dropped: {len(duplicates)}, without EIK: {len(no_eik)})")
    sql.append("")
    sql.append("BEGIN;")
    sql.append("")
    sql.append("CREATE TEMP TABLE _partneri_stage (")
    sql.append("  name        VARCHAR(255) NOT NULL,")
    sql.append("  eik         VARCHAR(20),")
    sql.append("  vat_number  VARCHAR(20),")
    sql.append("  address     TEXT,")
    sql.append("  phone       TEXT,")
    sql.append("  contact_person VARCHAR(255)")
    sql.append(") ON COMMIT DROP;")
    sql.append("")

    def q(s: str) -> str:
        return s.replace("'", "''") if s else ""

    def lit(s: str) -> str:
        return f"'{q(s)}'" if s else "NULL"

    for r in rows:
        sql.append(
            "INSERT INTO _partneri_stage VALUES "
            f"({lit(r['name'])}, {lit(r['eik'])}, {lit(r['vat'])}, "
            f"{lit(r['address'])}, {lit(r['phone'])}, {lit(r['responsible'])});"
        )

    sql.extend([
        "",
        "-- UPSERT partners by EIK (Microinvest tax ID is the natural key).",
        "-- For rows without EIK, INSERT new (no matching needed).",
        "INSERT INTO partners (",
        "    name, eik, vat_number, address, phone, contact_person, partner_type",
        ")",
        "SELECT s.name, NULLIF(s.eik,''), NULLIF(s.vat_number,''), NULLIF(s.address,''),",
        "       NULLIF(s.phone,''), NULLIF(s.contact_person,''), 'customer'",
        "  FROM _partneri_stage s;",
        "",
        "DO $$",
        "DECLARE p INT;",
        "BEGIN",
        "  SELECT COUNT(*) INTO p FROM partners;",
        "  RAISE NOTICE 'partners after import: %', p;",
        "END $$;",
        "",
        "COMMIT;",
        "",
    ])

    OUT_SQL.write_text("\n".join(sql), encoding="utf-8")

    # ---- Report ----
    print(f"parsed rows:           {len(rows)}")
    print(f"  with EIK:            {len(rows) - len(no_eik)}")
    print(f"  without EIK:         {len(no_eik)}")
    print(f"orphans (EIK as name): {len(orphans)}")
    print(f"duplicates dropped:    {len(duplicates)}")
    print()
    print(f"-> CSV: {OUT_CSV}")
    print(f"-> SQL: {OUT_SQL}")
    if duplicates[:5]:
        print()
        print("Sample duplicates:")
        for ln, eik, name in duplicates[:5]:
            print(f"  L{ln} EIK={eik} {name!r}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
