#!/usr/bin/env python3
"""Parse ЖЕЛЕЗАРИЯ.txt fixed-width Microinvest report -> CSV + SQL UPSERT."""
from __future__ import annotations
import csv
import re
import sys
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Optional

SRC = Path("/Users/magic/Projects/mert-m/data-imports/zhelezarya.utf8.txt")
OUT_CSV = Path("/Users/magic/Projects/mert-m/data-imports/zhelezarya.csv")
OUT_SQL = Path("/Users/magic/Projects/mert-m/data-imports/zhelezarya-import.sql")
GROUP_NAME = "ЖЕЛЕЗАРИЯ"

UNIT_MAP = {
    "БР":       "pcs",
    "БР.":      "pcs",
    "КГ":       "kg",
    "КГ.":      "kg",
    "МЕТРИ":    "m",
    "М":        "m",
    "М.":       "m",
    "КОМПЛЕКТ": "set",
    "К-Т":      "set",
    "КУТИЯ":    "box",
    "ПАКЕТ":    "pack",
    "РОЛКА":    "roll",
    "СТЕК":     "pack",
    "ТОП":      "bundle",
}

# Fixed-width column boundaries (CHARACTER positions, after stripping the
# 10-space leading indent). Inferred from the header & data rows:
#
#   "          Код             Стока                          Мярка   Количество     Доставна цена              Общо"
#   "          03090019        22003 МАКЕЛ КЛЮЧ 2-ен МИМОЗА   БР.         45.000              1.21             54.44"
#
# Slicing is character-based (not byte-based) so Cyrillic is handled correctly.
COLS = {
    "code":    (0, 16),
    "name":    (16, 47),
    "unit":    (47, 55),
    "qty":     (55, 70),
    "price":   (70, 90),
    "total":   (90, 110),
}

ITEM_RE = re.compile(r"^ {10}\S")        # data row: 10 spaces + non-space char
SKIP_LINES = {
    "СПРАВКА ЗА НАЛИЧНОСТИТЕ",
    "ЖЕЛЕЗАРИЯ",
    "Код",
    "стр.",
    "ОБЩО ЗА ОБЕКТА:",
    "Дата:",
}


def parse_decimal(token: str) -> Optional[Decimal]:
    token = token.strip()
    if not token:
        return None
    try:
        return Decimal(token)
    except InvalidOperation:
        return None


def is_skippable(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return True
    if stripped.startswith("---") or stripped.startswith("==="):
        return True
    for marker in SKIP_LINES:
        if marker in stripped:
            return True
    return False


def slice_columns(payload: str) -> dict:
    return {key: payload[a:b].strip() for key, (a, b) in COLS.items()}


def main() -> int:
    rows = []
    duplicates = []
    seen_codes = {}
    weird = []

    with SRC.open(encoding="utf-8") as f:
        for lineno, raw in enumerate(f, start=1):
            line = raw.rstrip("\r\n")
            if not ITEM_RE.match(line):
                continue
            if is_skippable(line):
                continue

            payload = line[10:]               # drop 10-space indent
            cols = slice_columns(payload)
            code = cols["code"]
            name = cols["name"]
            unit_raw = cols["unit"]
            qty = parse_decimal(cols["qty"])
            price = parse_decimal(cols["price"])

            # Validate row: must have code + name + qty + price
            if not code or not name or qty is None or price is None:
                weird.append((lineno, line))
                continue

            unit = UNIT_MAP.get(unit_raw.upper(), unit_raw)
            if code in seen_codes:
                duplicates.append((code, seen_codes[code], lineno))
            else:
                seen_codes[code] = lineno

            rows.append({
                "lineno": lineno,
                "code": code,
                "name_bg": name,
                "unit_raw": unit_raw,
                "unit": unit,
                "quantity": qty,
                "purchase_price": price,
            })

    # ---- CSV ----
    with OUT_CSV.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["microinvest_code", "name_bg", "unit_raw", "unit", "quantity", "purchase_price"])
        for r in rows:
            w.writerow([r["code"], r["name_bg"], r["unit_raw"], r["unit"], r["quantity"], r["purchase_price"]])

    # ---- SQL UPSERT ----
    sql_lines = [
        "-- ЖЕЛЕЗАРИЯ stock import — generated by parse_zhelezarya.py",
        f"-- Source: {SRC.name}  (1144 lines)",
        f"-- Items: {len(rows)}",
        "",
        "BEGIN;",
        "",
        "-- Stage rows in a temp table, then upsert products + inventory",
        "CREATE TEMP TABLE _zhelezarya_stage (",
        "  microinvest_code VARCHAR(50) NOT NULL,",
        "  name_bg          VARCHAR(255) NOT NULL,",
        "  unit             VARCHAR(20)  NOT NULL,",
        "  quantity         NUMERIC(12,3) NOT NULL,",
        "  purchase_price   NUMERIC(10,2) NOT NULL",
        ") ON COMMIT DROP;",
        "",
    ]

    def sql_quote(s: str) -> str:
        return s.replace("'", "''")

    for r in rows:
        sql_lines.append(
            "INSERT INTO _zhelezarya_stage VALUES "
            f"('{sql_quote(r['code'])}', '{sql_quote(r['name_bg'])}', "
            f"'{sql_quote(r['unit'])}', {r['quantity']}, {r['purchase_price']});"
        )

    sql_lines.extend([
        "",
        "-- 1) UPSERT products by microinvest_code",
        "INSERT INTO products (",
        "    name_bg, name_en, sku, microinvest_code, group_name, unit, purchase_price, is_active",
        ")",
        "SELECT s.name_bg, s.name_bg, s.microinvest_code, s.microinvest_code,",
        f"       '{GROUP_NAME}', s.unit, s.purchase_price, true",
        "  FROM _zhelezarya_stage s",
        "ON CONFLICT (sku) DO UPDATE SET",
        "    name_bg          = EXCLUDED.name_bg,",
        "    microinvest_code = EXCLUDED.microinvest_code,",
        "    group_name       = COALESCE(products.group_name, EXCLUDED.group_name),",
        "    unit             = EXCLUDED.unit,",
        "    purchase_price   = EXCLUDED.purchase_price,",
        "    updated_at       = NOW();",
        "",
        "-- 2) UPSERT inventory in default warehouse (id = 1)",
        "--    Uses (product_id, batch_id, warehouse_id) UNIQUE constraint;",
        "--    batch_id IS NULL because MERT-M sells durable goods.",
        "INSERT INTO inventory (product_id, batch_id, warehouse_id, quantity)",
        "SELECT p.id, NULL, 1, s.quantity",
        "  FROM _zhelezarya_stage s",
        "  JOIN products p ON p.microinvest_code = s.microinvest_code",
        "ON CONFLICT (product_id, batch_id, warehouse_id) DO UPDATE SET",
        "    quantity   = EXCLUDED.quantity,",
        "    updated_at = NOW();",
        "",
        "-- Sanity checks",
        "DO $$",
        "DECLARE",
        "  staged INT;",
        "  product_count INT;",
        "  inv_count INT;",
        "BEGIN",
        "  SELECT COUNT(*) INTO staged FROM _zhelezarya_stage;",
        f"  SELECT COUNT(*) INTO product_count FROM products WHERE group_name = '{GROUP_NAME}';",
        "  SELECT COUNT(*) INTO inv_count",
        "    FROM inventory i",
        "    JOIN products p ON p.id = i.product_id",
        f"   WHERE p.group_name = '{GROUP_NAME}' AND i.warehouse_id = 1;",
        "  RAISE NOTICE 'staged=%  products=%  inventory=%', staged, product_count, inv_count;",
        "END $$;",
        "",
        "-- COMMIT;  -- uncomment to apply, leave as ROLLBACK for dry run",
        "ROLLBACK;",
        ""
    ])

    OUT_SQL.write_text("\n".join(sql_lines), encoding="utf-8")

    # ---- Report ----
    qty_total = sum(r["quantity"] for r in rows)
    cost_total = sum(r["quantity"] * r["purchase_price"] for r in rows)

    print(f"parsed rows:     {len(rows)}")
    print(f"unique codes:    {len(seen_codes)}")
    print(f"duplicate codes: {len(duplicates)}")
    print(f"weird/skipped:   {len(weird)}")
    print(f"qty total:       {qty_total}    (expected 76415.980)")
    print(f"cost total:      {cost_total:.2f}  (expected 45537.14)")
    print()
    print(f"-> CSV: {OUT_CSV}")
    print(f"-> SQL: {OUT_SQL}")

    if duplicates:
        print()
        print("DUPLICATES (code, first-line, second-line):")
        for d in duplicates[:20]:
            print(" ", d)

    if weird:
        print()
        print("UNPARSED LINES (first 10):")
        for ln, raw in weird[:10]:
            print(f"  {ln}: {raw!r}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
